# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Create Maven Artifacts
      run: mvn package -Dmaven.test.skip=true

    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Kill Java Processes
      run: az vm run-command invoke -g Cloud-Final-Project_group -n Cloud-Final-Project --command-id KillJavaProc --scripts "sudo pkill -f 'java -jar"
    
    - name: Delete Old Jar
      run: az vm run-command invoke -g Cloud-Final-Project_group -n Cloud-Final-Project --command-id DeleteOldJar --scripts "sudo rm /home/azureuser/java/assignment1-0.0.1-SNAPSHOT.jar"
       
    - name: Add SSH
      uses: shimataro/ssh-key-action@v2.1.0
      with:
        key: ${{ secrets.AZURE_SSH_PEM }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
    - name: Upload New Jar
      run: scp target/assignment1-0.0.1-SNAPSHOT.jar azureuser@cloudfinalproject.eastus.cloudapp.azure.com:/home/azureuser/java
    
    - name: Run Jar
      run: az vm run-command invoke -g Cloud-Final-Project_group -n Cloud-Final-Project --command-id RunJar --scripts "java -jar /home/azureuser/java/assignment1-0.0.1-SNAPSHOT.jar"

    
