# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - run: mkdir -p development/artifacts
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Create Maven Artifacts
      run: mvn package -Dmaven.test.skip=true

    - name: Add SSH
      uses: shimataro/ssh-key-action@v2.1.0
      with:
        key: ${{ secrets.AZURE_SSH_PEM }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
    - name: upload new jar using SCP
      run: scp target/assignment1-0.0.1-SNAPSHOT.jar azureuser@cloudfinalproject.eastus.cloudapp.azure.com:home/azureuser/java
    
